task: cont_space_llm_num_optim
num_episodes: 400
gym_env_name: Pong-v0
render_mode: null
logdir: logs/pong_props
dim_actions: 3
dim_states: 5
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: num_optim.j2
llm_output_conversion_template_name: num_optim.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
bias: true
optimum: 3
search_step_size: 1.0
