task: cont_state_llm_num_optim_semantics
num_episodes: 400
gym_env_name: Swimmer-v5
render_mode: null
logdir: logs/swimmer_propsp
dim_actions: 2
dim_states: 8
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: num_optim_semantic.j2
llm_output_conversion_template_name: num_optim_semantic.j2
llm_model_name: ollama:gpt-oss:20b
num_evaluation_episodes: 20
warmup_episodes: 100
warmup_dir: null
bias: true
optimum: 250
search_step_size: 0.1
env_desc_file: env_descriptions/swimmer.j2
ollama_num_ctx: 4096
include_trajectories: false
