task: cont_state_llm_num_optim_semantics
num_episodes: 400
gym_env_name: InvertedPendulum-v5
render_mode: null
logdir: logs/invertedpendulum_propsp
dim_actions: 1
dim_states: 4
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: num_optim_semantic.j2
llm_output_conversion_template_name: num_optim_semantic.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
bias: true
optimum: 1000
search_step_size: 1.0
env_desc_file: env_descriptions/invertedpendulum.j2
