task: cont_state_llm_num_optim_semantics
num_episodes: 400
gym_env_name: Walker2d-v5
render_mode: null
logdir: logs/walker2d_propsp
dim_actions: 6
dim_states: 17
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: num_optim_semantic.j2
llm_output_conversion_template_name: num_optim_semantic.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
bias: true
optimum: 7000
search_step_size: 0.1
env_desc_file: env_descriptions/walker2d.j2
