task: cont_state_llm_num_optim_semantics_with_feedback
num_episodes: 400
gym_env_name: Walker2d-v5
render_mode: null
logdir: logs/walker2d_propspf
dim_actions: 6
dim_states: 17
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: num_optim_semantic_feedback.j2
llm_output_conversion_template_name: num_optim_semantic_feedback.j2
llm_model_name: ollama:deepseek-r1:8b
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
bias: true
optimum: 7000
search_step_size: 0.1
env_desc_file: env_descriptions/walker2d.j2
ollama_num_ctx: 16384
include_trajectories: false
include_feedback_with_params: true
feedback_interval: 5
param_min: -6.0
param_max: 6.0