task: cont_state_llm_num_optim_semantics
num_episodes: 100
gym_env_name: MountainCar-v0
render_mode: null
logdir: logs/mountaincar_propsp
dim_actions: 3
dim_states: 2
max_traj_count: 1000
max_traj_length: 200
template_dir: agent/policy/templates
llm_si_template_name: num_optim_semantic.j2
llm_output_conversion_template_name: num_optim_semantic.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 20
warmup_episodes: 0
warmup_dir: null
bias: true
optimum: -120
search_step_size: 1.0
env_desc_file: env_descriptions/mountaincar.j2
